import streamlit as st
import pandas as pd
import joblib
from pathlib import Path

# ---------------- PAGE CONFIG ---------------- #

st.set_page_config(
    page_title="CardioPredict AI",
    page_icon="❤️",  
    layout="wide"
)

# ---------------- LOAD FILES ---------------- #

BASE_DIR = Path(__file__).parent

model = joblib.load(BASE_DIR / "SVC_model.joblib")
scaler = joblib.load(BASE_DIR / "scaler.joblib")
expected_columns = joblib.load(BASE_DIR / "columns.joblib")

# ---------------- CUSTOM CSS ---------------- #

st.markdown("""
<style>

.block-container {
    padding-top: 2rem;
}

.stButton > button {
    width: 100%;
    height: 60px;
    border-radius: 15px;
    font-size: 18px;
    font-weight: bold;
}

div[data-testid="stMetric"] {
    background-color: #262730;
    border-radius: 10px;
    padding: 10px;
}

</style>
""", unsafe_allow_html=True)

# ---------------- HEADER ---------------- #

st.markdown("""
<h1 style='text-align:center;color:#FF4B4B;'>
CardioPredict AI
</h1>

<h4 style='text-align:center;'>
Machine Learning Based Heart Disease Predictor
</h4>
""", unsafe_allow_html=True)

st.info(
    "⚠️ This prediction is generated by a Machine Learning model and should not replace professional medical advice."
)

st.divider()

# ---------------- SIDEBAR ---------------- #

with st.sidebar:

    st.markdown("# 📊 CardioPredict AI")

    st.markdown("### Smart Heart Risk Assessment")

    st.divider()

    st.markdown("""
### 📋 Parameters Used

• Age

• Blood Pressure

• Cholesterol

• ECG Results

• Maximum Heart Rate

• Exercise Angina

• ST Depression
""")

    st.divider()

    st.markdown("""
### ❤️ Heart Health Tips

🥗 Eat healthy foods

🚶 Exercise regularly

💧 Stay hydrated

😴 Sleep 7–8 hours

🚭 Avoid smoking

🩺 Regular health checkups
""")

    st.divider()

    st.caption("Developed by supremeinferno😳 ")

# ---------------- INPUT SECTION ---------------- #

col1, col2 = st.columns(2)

with col1:

    age = st.slider("Age", 18, 100, 40)

    sex = st.selectbox(
        "Sex",
        ["M", "F"]
    )

    resting_bp = st.number_input(
        "Resting Blood Pressure (mm Hg)",
        80,
        200,
        120
    )

    cholesterol = st.number_input(
        "Cholesterol (mg/dL)",
        100,
        600,
        200
    )

    fasting_bs = st.selectbox(
        "Fasting Blood Sugar > 120 mg/dL",
        [0, 1]
    )

with col2:

    chest_pain = st.selectbox(
        "Chest Pain Type",
        ["ATA", "NAP", "TA", "ASY"]
    )

    resting_ecg = st.selectbox(
        "Resting ECG",
        ["Normal", "ST", "LVH"]
    )

    max_hr = st.slider(
        "Max Heart Rate",
        60,
        220,
        150
    )

    exercise_angina = st.selectbox(
        "Exercise-Induced Angina",
        ["Y", "N"]
    )

    oldpeak = st.slider(
        "Oldpeak (ST Depression)",
        0.0,
        6.0,
        1.0
    )

    st_slope = st.selectbox(
        "ST Slope",
        ["Up", "Flat", "Down"]
    )

st.divider()

# ---------------- PREDICTION ---------------- #

if st.button("🔍 Predict Heart Disease Risk"):

    input_data = {col: 0 for col in expected_columns}

    # Numerical Features
    input_data["Age"] = age
    input_data["RestingBP"] = resting_bp
    input_data["Cholesterol"] = cholesterol
    input_data["FastingBS"] = fasting_bs
    input_data["MaxHR"] = max_hr
    input_data["Oldpeak"] = oldpeak

    # Encoded Features
    if f"Sex_{sex}" in input_data:
        input_data[f"Sex_{sex}"] = 1

    if f"ChestPainType_{chest_pain}" in input_data:
        input_data[f"ChestPainType_{chest_pain}"] = 1

    if f"RestingECG_{resting_ecg}" in input_data:
        input_data[f"RestingECG_{resting_ecg}"] = 1

    if f"ExerciseAngina_{exercise_angina}" in input_data:
        input_data[f"ExerciseAngina_{exercise_angina}"] = 1

    if f"ST_Slope_{st_slope}" in input_data:
        input_data[f"ST_Slope_{st_slope}"] = 1

    input_df = pd.DataFrame([input_data])

    try:

        # KEEP THIS AS YOUR WORKING VERSION
        scaled_input = scaler.transform(input_df)

        prediction = model.predict(scaled_input)[0]
        probability = model.predict_proba(scaled_input)[0]

        risk_percentage = probability[1] * 100
        safe_percentage = probability[0] * 100

        st.divider()

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "⚠️ Heart Disease Risk",
                f"{risk_percentage:.2f}%"
            )

        with col2:
            st.metric(
                "✅ Healthy Probability",
                f"{safe_percentage:.2f}%"
            )


        if prediction == 1:

            st.progress(min(int(risk_percentage), 100))

            st.error(
                f"⚠️ High Risk of Heart Disease ({risk_percentage:.2f}%)"
            )

            st.markdown("""
### Recommended Actions

• Consult a cardiologist

• Monitor blood pressure regularly

• Reduce cholesterol intake

• Follow a healthy diet

• Exercise under medical guidance

• Avoid smoking
""")

        else:

            st.progress(min(int(safe_percentage), 100))

            st.success(
                f"✅ Low Risk of Heart Disease ({safe_percentage:.2f}%)"
            )

            st.markdown("""
### Recommendations

• Continue healthy eating

• Stay physically active

• Maintain regular health checkups

• Monitor blood pressure regularly

• Maintain a healthy lifestyle
""")

    except Exception as e:

        st.error(f"Error: {e}")

        st.write("Expected Columns:")
        st.write(expected_columns)

        st.write("Input Columns:")
        st.write(input_df.columns.tolist())



#python3 -m streamlit run app.py